export const data = [
  {
    id: 1,
    title: "The Image Title",
    img: "./images/image (1).jpg",
    price: 20,
    body: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. ",
  },
  {
    id: 2,
    title: "The Image Title",
    img: "/images/image (2).jpg",
    price: 20,
    body: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. ",
  },
  {
    id: 3,
    title: "The Image Title",
    img: "/images/image (3).jpg",
    price: 20,
    body: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. ",
  },
  {
    id: 4,
    title: "The Image Title",
    img: "/images/image (4).jpg",
    price: 20,
    body: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. ",
  },
  {
    id: 5,
    title: "The Image Title",
    img: "/images/image (5).jpg",
    price: 20,
    body: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. ",
  },
  {
    id: 6,
    title: "The Image Title",
    img: "/images/image (6).jpg",
    price: 20,
    body: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. ",
  },
  {
    id: 7,
    title: "The Image Title",
    img: "/images/image (7).jpg",
    price: 20,
    body: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. ",
  },
  {
    id: 8,
    title: "The Image Title",
    img: "/images/image (8).jpg",
    price: 20,
    body: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. ",
  },
  {
    id: 9,
    title: "The Image Title",
    img: "/images/image (9).jpg",
    price: 20,
    body: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. ",
  },
  {
    id: 10,
    title: "The Image Title",
    img: "/images/image (10).jpg",
    price: 20,
    body: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. ",
  },
  {
    id: 11,
    title: "The Image Title",
    img: "/images/image (11).jpg",
    price: 20,
    body: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. ",
  },
  {
    id: 12,
    title: "The Image Title",
    img: "/images/image (12).jpg",
    price: 20,
    body: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. ",
  },
  {
    id: 13,
    title: "The Image Title",
    img: "/images/image (13).jpg",
    price: 20,
    body: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. ",
  },
  {
    id: 14,
    title: "The Image Title",
    img: "/images/image (14).jpg",
    price: 20,
    body: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. ",
  },
  {
    id: 15,
    title: "The Image Title",
    img: "/images/image (15).jpg",
    price: 20,
    body: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. ",
  },
  {
    id: 16,
    title: "The Image Title",
    img: "/images/image (16).jpg",
    price: 20,
    body: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. ",
  },
  {
    id: 17,
    title: "The Image Title",
    img: "/images/image (17).jpg",
    price: 20,
    body: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. ",
  },
  {
    id: 18,
    title: "The Image Title",
    img: "/images/image (18).jpg",
    price: 20,
    body: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. ",
  },
  {
    id: 19,
    title: "The Image Title",
    img: "/images/image (19).jpg",
    price: 20,
    body: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. ",
  },
  {
    id: 20,
    title: "The Image Title",
    img: "/images/image (20).jpg",
    price: 20,
    body: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. ",
  },
];
